// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg4Ivqe0orOPotg_AyNvMhC0wkstSm4lQ',
    appId: '1:842365244917:web:d6c6887ccad5cf8accfcbc',
    messagingSenderId: '842365244917',
    projectId: 'palp-uas-22100032',
    authDomain: 'palp-uas-22100032.firebaseapp.com',
    storageBucket: 'palp-uas-22100032.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMXHvoM_LyjpPYJPDcpa9fiNJ5MOQUSWE',
    appId: '1:842365244917:android:27fa79a4488f8cb0ccfcbc',
    messagingSenderId: '842365244917',
    projectId: 'palp-uas-22100032',
    storageBucket: 'palp-uas-22100032.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANfdeyWgYk5ck4sbj0IJAF08rGmLu6I3s',
    appId: '1:842365244917:ios:26c84ba91aa8c961ccfcbc',
    messagingSenderId: '842365244917',
    projectId: 'palp-uas-22100032',
    storageBucket: 'palp-uas-22100032.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANfdeyWgYk5ck4sbj0IJAF08rGmLu6I3s',
    appId: '1:842365244917:ios:26c84ba91aa8c961ccfcbc',
    messagingSenderId: '842365244917',
    projectId: 'palp-uas-22100032',
    storageBucket: 'palp-uas-22100032.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCg4Ivqe0orOPotg_AyNvMhC0wkstSm4lQ',
    appId: '1:842365244917:web:d8e8125362761bf2ccfcbc',
    messagingSenderId: '842365244917',
    projectId: 'palp-uas-22100032',
    authDomain: 'palp-uas-22100032.firebaseapp.com',
    storageBucket: 'palp-uas-22100032.firebasestorage.app',
  );
}
